nome = input('Qual é seu nome completo? ')
min = nome.lower()
mai = nome.upper()
lt = len(nome.replace(" ",""))
print('Este nome tem {} letras.'.format(lt))
print('Este nome em minusculas é {}.'.format(min))
print('Este nome em maiusculas é {}.'.format(mai))
div = nome.split()
lpn = len(div[0])
print('O primeiro nome dessa pessoa tem {} letras.'.format(lpn))