nome = str(input('Qual é seu nome completo? ')).strip().capitalize()
min = nome.lower()
mai = nome.upper()
print('Analisando seu nome...')
lt = len(nome.replace(" ",""))
print('Este nome em maiusculas é {}.'.format(mai))
print('Este nome em minusculas é {}.'.format(min))
print('Este nome tem {} letras.'.format(lt))
div = nome.split()
lpn = len(div[0])
print('O primeiro nome dessa pessoa tem {} letras.'.format(lpn))