times = ('Palmeiras', 'Corinthians', 'Flamengo','Fluminense','Athletico PR','Internacional','Atlético-MG','Red Bull Bragantino','América-MG','Santos','São Paulo','Botafogo','Goiás','Ceará SC','Coritiba','Avaí','Cuiabá','Atlético-GO','Fortaleza','Juventude', 'Chapecoense')
print('=-'*20)
print(f'Lista de times do Campeonato Brasileiro: {times}')
print('=-'*20)
print(f'Os 5 primeiros times são: {times[0:5]}')
print('=-'*20)
print(f'Os 4 últimos colocados são: {times[-4:]}')
print('=-'*20)
print(f'Times em ordem alfabética: {sorted(times)}')
print('=-'*20)
print(f'O Chapecoense está na {times.index("Chapecoense")+1}ª posição')
print('=-'*20)